### ISSUE TITLE
Add / edit record in usermeta table?

### ISSUE THREAD

**Issue by hbcondo** [wp-net/WordPressPCL#160] opened 2019-02-11 05:09 UTC
Could you please provide an example of how to add or edit a record in the WordPress `usermeta` table using the `User.Update` method? Thank you.

**Comment by ThomasPe** [comment] 2019-12-27 12:48
Duplicate of https://github.com/wp-net/WordPressPCL/issues/163

**Closed by ThomasPe** 2019-12-27 12:48 UTC
